### ISSUE TITLE
/Applications directory

### ISSUE THREAD

**Issue by probonopd** [glowiak/Minecraft-helloapp#1]
hello @glowiak, thanks for making an `.app` bundle for helloSystem.

> After unzip the app HAVE to be placed in /Applications directory!!!

Why? It works fine for me if I e.g., extract it to the Desktop, or to one of the sub-folders in `/Applications`... as it should be.

Maybe you wanted to write "SHOULD" rather than "HAVE to be"?

**Comment by glowiak** [comment]
then it did work only in /Applications

**Comment by probonopd** [comment]
That's not how it should be ;)
